# Generated by Django 5.0.7 on 2024-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.CharField(max_length=450, unique=True),
        ),
    ]
